# Generated by Django 6.0.4 on 2026-05-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0003_split_subscribed_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriberemail",
            name="subscribed_blog",
            field=models.BooleanField(default=False),
        ),
    ]
