# Generated by Django 6.0.4 on 2026-05-05 14:18

from django.db import migrations, models


def mark_existing_not_new(apps, schema_editor):
    SubscriberEmail = apps.get_model("mailing", "SubscriberEmail")
    SubscriberEmail.objects.all().update(is_new=False)


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0004_alter_subscriberemail_subscribed_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberemail",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(mark_existing_not_new, migrations.RunPython.noop),
    ]
