# Generated by Django 6.0.4 on 2026-05-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0005_add_is_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriberemail",
            name="google_authenticated",
            field=models.BooleanField(default=False, verbose_name="Google"),
        ),
        migrations.AlterField(
            model_name="subscriberemail",
            name="subscribed_blog",
            field=models.BooleanField(default=False, verbose_name="Blog"),
        ),
        migrations.AlterField(
            model_name="subscriberemail",
            name="subscribed_wall",
            field=models.BooleanField(default=False, verbose_name="Wall"),
        ),
    ]
