# Generated by Django 6.0.4 on 2026-05-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0006_alter_subscriberemail_google_authenticated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriberemail",
            name="google_authenticated",
            field=models.BooleanField(
                default=False,
                help_text="Whether Google has authenticated this email address",
                verbose_name="Google",
            ),
        ),
        migrations.AlterField(
            model_name="subscriberemail",
            name="is_new",
            field=models.BooleanField(
                default=True,
                help_text="Changes to False once the user saves their subscription for the first time.",
            ),
        ),
        migrations.AlterField(
            model_name="subscriberemail",
            name="subscribed_blog",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user will get emails for blog.evanchen.cc",
                verbose_name="Blog",
            ),
        ),
        migrations.AlterField(
            model_name="subscriberemail",
            name="subscribed_wall",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user will get emails for blog.evanchen.cc",
                verbose_name="Wall",
            ),
        ),
    ]
