# Generated by Django 6.0.4 on 2026-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0007_alter_subscriberemail_google_authenticated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriberemail",
            name="subscribed_wall",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user will get emails for wall.evanchen.cc",
                verbose_name="Wall",
            ),
        ),
    ]
